### ISSUE TITLE
Bloqueios temporários da receita a meu servidor/aplicação

### ISSUE THREAD

**Issue by Bavaresco** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#10]
Notei recentemente bloqueios vindos por parte da Receita, não tenho como provar mas acredito ser da Receita. O script do nada para de chamar a imagem do captcha, isso por que diariamente tenho mais de 16 mil acessos nesta página onde está a consulta, então acredito que a receita tenha algum controle e bloqueio quanto a isto.

A pergunta: **É possível usar algum tipo de proxy ou mascarador de IP para que a receita não bloqueie o site?** Pois não consigo manter o script online, funciona um pouco e logo para de funcionar...

EDIT - Ja dei uma olhada na net, e da pra configurar um proxy no curl..você já fez isto? Qual proxy comprou para tal?

**Comment by Massa191** [comment]
Nunca usei Proxy no Curl.
Alerto que a utilização de proxy torna os dados mais vulneráveis, e possivelmente gerará maior lentidão na consulta.
Difícil encontrar bons proxys.
Quanto ao suposto "bliqueio" , informo que nos últimos 2 dias me foram relatados por outros usuários problemas semelhantes , mas nenhum se confirmou definitivamente como bloqueio.
Eu já fui bloqueado no passado, e só resolvi mudando o servidor da hospedagem.
Problemas intermitentes não necessariamente  configuram bloqueio

**Comment by Bavaresco** [comment]
Realmente, é dificil...já tentei aqui com vários. Vou continuar tentando e informo se eu conseguir.

**Comment by Massa191** [comment]
Olá Bavaresco
Scripts atualizados e otimizados.
Verifique por favor a utilização desta última atualização de 01-06-2017
