### ISSUE TITLE
Erro ao consultar CNPJ  em servidor linux

### ISSUE THREAD

**Issue by FabioTTCA** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#12]
Boa tarde,

Utilizei seu script em ambiente local windows e não apresentou nenhum erro mas em nosso servidor linux, ao consultar um CNPJ, é dado sempre a menssagem "Imagem digitada incorretamente", há algo que possa ser feito para corrigir este erro?

**Comment by Massa191** [comment]
Aqui está funcionando normalmente em ambiente Linux

Verifique se o Cookie está sendo gerado dentro da pasta cookies, na primeira geração do Captcha
Verifique se o atributo flag=1 está sendo gravado no mesmo cookie acima na submissão dos dados para a receita

Se isto não estiver ocorrendo, vc. terá esta mensagem de erro.

Neste caso, é necessário que seu PHP tenha permissão de escrita na referida pasta.
Neste caso, Verifique também a diretiva allow url fopen de seu php

Abraço
