### ISSUE TITLE
Ajuda

### ISSUE THREAD

**Issue by geracaodelider** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#13]
Marcos, tudo bem?
Primeiro gostaria de parabenizar pelo trabalho realizado.

Estamos utilizando sua API, e por algum tempo funcionou perfeitamente.

Porém agora, todas as consultas tem retornado: Receita não responde.

Sabe me dizer se isso é comum, se o site da receita fica muito fora do ar, por isso que recebemos esse retorno?

Obrigado

**Comment by Bavaresco** [comment]
Se foi ontem era problema da receita mesmo, o servidor da receita federal deve ser hospedado em uma calculadora de tão ruim que é e normalmente há sobrecargas e vários serviços param de funcionar...tenho aqui também consultas de CPF em alguns webservices diferentes e o problema também aconteceu ontem. Hoje está estável.

**Comment by Massa191** [comment]
Sim
Ultimamente tem ocorrido diversas instabilidades nos serviços da receita.
Ou sobrecarga , ou logo vem alguma novidade que vai nos fazer mudar tudo denovo .
Mas somos Brasileiros e não desistimos nunca

**Comment by Massa191** [comment]
Algumas vezes nota-se também um certo delay no re-estabelecimento  do serviço quando comparamos a consulta atraves do navegador de nosso PC e a API hospedada em algum servidor devido às diferentes rotas entre solicitação e resposta.
