### ISSUE TITLE
Implementação em codeigniter

### ISSUE THREAD

**Issue by jorgeanr** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#14]
Prezado, obrigado por compartilhar o código. Estou tentando implementá-lo em codeigniter, no entanto estou tendo um problema com a variável conteudo, do arquivo de getcaptcha. O php está retornando o seguinte erro:

Message: Undefined variable: conteudo
Filename: models/Captcha_model.php
Line Number: 64

O bloco da linha 64 é o seguinte:

					while (!feof($file)){
						$conteudo .= fread($file, 1024);
					}

Se tiver alguma dica será muito bem vinda!

Obrigado!

**Comment by Massa191** [comment]
Olá Jorgeanr

É praticamente impossível descobrir o erro a partir apenas da linha que o evidência.
O Aconselho a testar as consultas de CPF e CNPJ a partir do script original, certificando-se de que não existam erros em sua execução. Caso existam, provavelmente deve-se investigar as configurações de seu PHP em busca de sana-los.
Depois disso, tendo certeza de que tudo funciona, passe a implementa-lo em codeigniter

Abraço

**Comment by urielb** [comment]
O script original está retornando o mesmo erro para mim. Com a adição de alguns:

```
Notice: Undefined variable: conteudo in C:\xampp\htdocs\numeroReceita\getcaptcha.php on line 55

Notice: Undefined offset: -1 in C:\xampp\htdocs\numeroReceita\getcaptcha.php on line 60

Notice: Undefined offset: 1 in C:\xampp\htdocs\numeroReceita\getcaptcha.php on line 124
```
usando a última instalação do XAMPP com PHP 5.6

**Comment by jorgeanr** [comment]
Prezados, mesmo com o erro o código está funcionando. Como o erro estava
impactando no retorno da minha chamada ajax, retornava o erro + o json eu
coloquei um error_reporting(E_ALL & ~E_NOTICE); na primeira linha da função
getHtmlCNPJ para tirar a sujeira dos notices e retornar apenas o json.

public function getHtmlCNPJ($cnpj, $captcha)
{
error_reporting(E_ALL & ~E_NOTICE);
$pasta_cookies = 'assets/cookies/';
define('COOKIELOCAL', str_replace('\\', '/',
realpath('./')).'/'.$pasta_cookies);

Jorge

**Comment by jorgeanr** [comment]
Eu cheguei a rodar o programa limpo do jeito que foi disponibilizado
gentilmente pelo Marcos em uma instalação MAMP do bitnami. Ele rodou
perfeito, sem os erros.

Os mesmos só apareceram para mim quando eu coloquei na estrutura do
codeigniter.

Jorge

2017-11-01 14:11 GMT-02:00 Jorge Rodrigues <jorgeanr@gmail.com>:

> Prezados, mesmo com o erro o código está funcionando. Como o erro estava
> impactando no retorno da minha chamada ajax, retornava o erro + o json eu
> coloquei um error_reporting(E_ALL & ~E_NOTICE); na primeira linha da função
> getHtmlCNPJ para tirar a sujeira dos notices e retornar apenas o json.
>
> public function getHtmlCNPJ($cnpj, $captcha)
> {
> error_reporting(E_ALL & ~E_NOTICE);
> $pasta_cookies = 'assets/cookies/';
> define('COOKIELOCAL', str_replace('\\', '/', realpath('./')).'/'.$pasta_
> cookies);
>
> Jorge
>

**Comment by urielb** [comment]
Para mim as imagens dos captchas não estão carregando, mas percebi que não tem a ver com esses notices, mas ainda não descobri o motivo.

**Comment by jorgeanr** [comment]
Pode ser as permissões da pasta.
