### ISSUE TITLE
Erro reCAPTCHA

### ISSUE THREAD

**Issue by fjsjr** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#16]
Parou de funcionar devido a troca do sistema de capcha da receita, tentei trocar a url como vi em outros lugares mais mesmo assim não funciona

url antiga = https://www.receita.fazenda.gov.br/pessoajuridica/cnpj/cnpjreva/Cnpjreva_Solicitacao2.asp

url Nova = https://www.receita.fazenda.gov.br/pessoajuridica/cnpj/cnpjreva/Cnpjreva_Solicitacao3.asp

**Comment by jorgeanr** [comment]
Estou com o mesmo problema. Poderiam disponibilizar uma API.

**Comment by Massa191** [comment]
Projeto Vivo novamente.
Atualizados os links e scripts para geração de Captcha "sonoro", enquanto a receita ainda os mantiver como opção de consulta além do Recaptcha
