### ISSUE TITLE
Contribuir com o projeto

### ISSUE THREAD

**Issue by Viniciusalopes** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#18]
Opa!
Enquanto implementava sua solução, encontrei algumas correções e melhorias.
Como faço para contribuir com o seu projeto?
Viniciusalopes.

**Comment by felipefinhane** [comment]
Talvez esse link lhe ajude ou de um ponta pé inicial para contribuir em repositórios.
https://imasters.com.br/desenvolvimento/como-contribuir-com-um-projeto-no-github/?trace=1519021197&source=single
