### ISSUE TITLE
Consulta com https - fix

### ISSUE THREAD

**Issue by clbonatto** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#2]
Com esta mudança para https, só consegui fazer funcionar o código inserindo a seguinte linha:
        curl_setopt($ch, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_0);

**Comment by gustavomac89** [comment]
Continua funcionando? Notei que o site está requisitando mais alguns cookies.

**Comment by clbonatto** [comment]
Sim, funcionando normalmente.

**Comment by clbonatto** [comment]
Criei um script simples para quem precisar testar.

https://github.com/clbonatto/ConsultaCPF

**Comment by diegoweb** [comment]
Será que vocês não conseguiriam implementar um sistema para preenchimento automático do captcha não?
Dêem uma olhada nesse script pré-pronto:http://www.rohitab.com/discuss/topic/26430-how-to-bypass-captcha/?p=10011074
Ou diretamente pelo Github:https://github.com/Dandeyl/ba/blob/master/_delete/server/captcha_solver.php
Pelo que percebi o sistema da Receita aceitaria essa "solução". Só é um pouco complicado para juntar com o script de vocês.
Tenho um sistema de preenchimento de formulário para clientes e utilizava a api do BIPBOP para obter o nome da pessoa através do CPF, porém como a receita trocou o sistema de CPF, a ferramenta quebrou =/ 
Era tão prático xD.

Date: Thu, 18 Aug 2016 06:20:49 -0700

**Comment by clbonatto** [comment]
Comecei alguns testes para resolver o captcha, porém não finalizei.

O mais simples seria fazer um BD com todas as combinações Base64 da imagem.

Se você fizer o cálculo, serão 26 letras minúsculas + 26 letras maiúsculas + números de 0-9 = 62 combinações por dígito.  

No caso, 62 \* 62 \* 62 \* 62 \* 62 \* 62 = 56.800.235.584. 

Para um banco de dados indexado, não é muita coisa, porém, vai bastante espaço no disco.

Bastaria criar um script para gerar todas as combinações e inserir no BD, e quando baixar o captcha confrontar nesse BD.

Outra opção é utilizar esses captchasolver, porém nunca testei.

Vou verificar esse script que você indicou.

Obrigado.

**Comment by clbonatto** [comment]
Testei alguns scripts, mas teria que adaptar para o captcha da receita mesmo. Não encontrei nenhum "plug and play".

Tem um tal de Tesseract, que é um OCR.

Aqui tem um projeto:
https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/master/src/TesseractOCR.php

E teve um ninja que pegou o áudio captcha e quebrou, segue o link.

http://hc0der.blogspot.com.br/2014/09/bypass-captcha-da-receita-federal.html

Como aqui na empresa, antes, os usuários precisavam entrar no site da receita, digitar CPF e data de nascimento, nesse formato de consulta "direta", a digitação do captcha não é empecilho.

**Comment by Massa191** [comment]
Pessoal
Atualizei os Scripts
Agora as consultas de CPF voltaram a funcionar
Abraços

**Comment by clbonatto** [comment]
Bom dia.

Desculpa Marcos, acabei deixando o tópico aberto, mas já foi resolvido há tempo.

Obrigado.
