### ISSUE TITLE
Mensagem imagem digitada Incorretamente

### ISSUE THREAD

**Issue by bvbneto** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#25]
Fala Marcos tudo bom,

Meu amigo, estou tentando usar seu script em um projeto mas mesmo tendo habilitado o acesso a pasta, trocado o endereço da receita no arquivos de funções e verificado a flag 1 no cookie que ele grava e verificado o allow url open ele continua mostrando que a imagem foi digitada de forma errada e retorna o array vazio!

Tens alguma idéia de mais algum item que pode estar gerando isso? 

Desde já te agradeço o retorno,

Um abraço,
Bruno

**Comment by Massa191** [comment]
Projeto Vivo novamente.
Atualizados os links e scripts para geração de Captcha "sonoro", enquanto a receita ainda os mantiver como opção de consulta além do Recaptcha
