### ISSUE TITLE
Na consulta do CPF o captcha agora é o ReCaptcha do google

### ISSUE THREAD

**Issue by RaphaelGNunes** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#26]
Na consulta do CPF o captcha agora é o ReCaptcha do google acredito que por isto esteja dando problema

**Comment by Massa191** [comment]
Projeto Vivo novamente.
Atualizados os links e scripts para geração de Captcha "sonoro", enquanto a receita ainda os mantiver como opção de consulta além do Recaptcha
