### ISSUE TITLE
Projeto Funcionando 

### ISSUE THREAD

**Issue by Massa191** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#27]
A Consulta de CPF , tinha parado devido a implementação do recaptcha do google.

As alterações realizadas hoje nos scripts permitem realizar as consultas de CNPJ e CPF utilizando os links de captcha Sonoro da Receita Federal, enquanto os mesmos estiverem ativos.

**Comment by bvbneto** [comment]
Oi Massa

Sabe o que pode estar ocorrendo pois já fiz inúmeros testes e sempre retorna como imagem digitada incorretamente porém ela está correta, sabe o que poderia estar ocorrendo?

desde já agradeço retorno,

Bvbneto

**Comment by Massa191** [comment]
Muito provavelmente não está gravando os cookies de sessão com a receita dentro da pasta cookies
