### ISSUE TITLE
Erro: "Receita não responde"

### ISSUE THREAD

**Issue by felipemarques** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#28]
Boa noite,

tentei de diversas formas utilizar esse repo para consulta do cpf com captcha, Porem sempre da o mesmo erro: Receita não responde

Poderia nos ajudar ?

Estou usando PHP Version 7.2.2-1+ubuntu16.04.1+deb.sury.org+1

**Comment by Massa191** [comment]
Atualizado hoje 26/03/2020
Funcionando as consultas de CPF e CNPJ para captcha Sonoro enquanto a receita as disponibilizar em paralelo ao recaptcha google

agradeçam ao COVID19 , que motivou-me a encontrar uma solução para viabilizar a utilização desta ferramenta em vossos e-comerce.
