### ISSUE TITLE
Consulta com erro

### ISSUE THREAD

**Issue by antonioaportt** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#29]
Boa tarde amigos,

Estou tentando usar a consulta mas esta me retornando erros.

Undefined variable: conteudo in C:\Antonio\Aportt Sistemas\Desenvolvimento\php\Consultas_CNPJ_CPF_Receita_Federal-master\getcaptcha.php on line 79
--
1 | 0.0017 | 365168 | {main}( ) | ...\index.php:0
2 | 0.0032 | 390528 | include( 'C:\Antonio\Aportt Sistemas\Desenvolvimento\php\Consultas_CNPJ_CPF_Receita_Federal-master\getcaptcha.php' ) | ...\index.php:10

e

Notice: Undefined variable: imagem_cpf in C:\Antonio\Aportt Sistemas\Desenvolvimento\php\Consultas_CNPJ_CPF_Receita_Federal-master\index.php on line 50 Call Stack #TimeMemoryFunctionLocation 10.0017365168{main}( )...\index.php:0 " border="0"> 

Já fiz alguns testes mas nao consigo ajustar.
Acredito que possa ser links da receita.

**Comment by Massa191** [comment]
Atualizado hoje 26/03/2020
Funcionando as consultas de CPF e CNPJ para captcha Sonoro enquanto a receita as disponibilizar em paralelo ao recaptcha google

agradeçam ao COVID19 , que motivou-me a encontrar uma solução para viabilizar a utilização desta ferramenta em vossos e-comerce.
