### ISSUE TITLE
Muito bom.

### ISSUE THREAD

**Issue by sineir** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#30]
obrigado por disponibilizar.....
fiz o script montar uma string sql. Casa consulta "OK" insere em um BD de teste

https://github.com/sineir/PHP/tree/master/cnpj

**Comment by dbrazoli** [comment]
Sineir, boa tarde.
Obrigado por compartilhar o seu código. Ficou show, sei que vc trabalhou num codigo de um outro colega e ficou muito bom.
Vc teria como ajudar com adicionando a consulta também ao QSA ?
