### ISSUE TITLE
Consulta de CPF não está funcionando

### ISSUE THREAD

**Issue by neovenom1** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#31]
Muito bom o seu projeto.
Coloquei em um servidor linux, com PHP 5.6. A consulta de CNPJ funciona perfeitamente, mas a **imagem do captcha para o CPF não está sendo gerada e a consulta de cpf não está funcionando.**

**Comment by Massa191** [comment]
Atualizado hoje 26/03/2020
Funcionando as consultas de CPF e CNPJ para captcha Sonoro enquanto a receita as disponibilizar em paralelo ao recaptcha google

agradeçam ao COVID19 , que motivou-me a encontrar uma solução para viabilizar a utilização desta ferramenta em vossos e-comerce.
