### ISSUE TITLE
Atualização do código

### ISSUE THREAD

**Issue by rafanake** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#32]
Tem planos para adaptar para nova versão do site da Receita?

**Comment by Massa191** [comment]
Atualizado hoje 26/03/2020
Funcionando as consultas de CPF e CNPJ para captcha Sonoro enquanto a receita as disponibilizar

agradeçam ao COVID19 , que motivou-me a encontrar uma solução para viabilizar a utilização desta ferramenta em vossos e-comerce.
