### ISSUE TITLE
Projeto Funcionando

### ISSUE THREAD

**Issue by Massa191** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#33]
Atualizado hoje 26/03/2020
Funcionando as consultas de CPF e CNPJ para captcha Sonoro enquanto a receita as disponibilizar em paralelo ao recaptcha google

agradeçam ao COVID19 , que motivou-me a encontrar uma solução para viabilizar a utilização desta ferramenta em vossos e-comerce.

**Comment by leocampra** [comment]
Show demais essa sua solução mas testando hj, apresenta a mensagem que " Imagem digitada incorretamente" para CNPJ

**Comment by Massa191** [comment]
Aqui funcionando Normal

**Comment by TiagoBani** [comment]
Aqui tambem só " Imagem digitada incorretamente" para CNPJ

**Comment by Massa191** [comment]
aqui funciona normal

Observe o formato para preenchimento (CNPJ ,... só numeros)
CPF , com caracteres (.-) e data com (/)

Se preencher em formato inadequado, a mensagem Imagem digitada incorretamente será retornada.

**Comment by mauricio-verissimo** [comment]
![image](https://user-images.githubusercontent.com/72482822/105444134-0e2c8280-5c4c-11eb-8599-e85ee93eced2.png)
 Não conseguir ainda implementar, mas dá esses erros acima, consulta funciona, mas apresenta esses erros

**Comment by Massa191** [comment]
Aqui funcionando normal

**Comment by Massa191** [comment]
![img_capt](https://user-images.githubusercontent.com/12865058/116570340-94f29a80-a8e0-11eb-8eea-d634acbbc452.jpg)
