### ISSUE TITLE
consulta em nodejs

### ISSUE THREAD

**Issue by tasca** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#34]
Amigo, vc pode fazer isso pra nodejs?

Posso ajudar.

**Comment by Massa191** [comment]
Olá

não conheço node.js , mas se tiver uma forma de fazer a consulta ao serviço nos moldes da biblioteca CURL do PHP utilizada em meus scripts, creio ser possível sim.

**Comment by tasca** [comment]
Amigo, nodejs é javascript para backend, muito facil o aprendizado.

vc pode explicar como funciona sua api?
pelo que entendo, é feito um acesso a uma pagina da RF e retorna uma form e
um captcha é isso?
como vc lida com o captcha, parece ser o segredo.

se puder entender como funciona, podemos fazer isso no node e será muito
usado, pois hoje é grande o nr de server nodejs.

fico no aguardo





Em qui., 29 de abr. de 2021 às 11:41, Marcos Peli ***@***.***>
escreveu:

**Comment by Massa191** [comment]
Olá Tasca

Não tem segredo
São feitas duas consultas via Biblioteca CURL, uma para captcha do CPF e outra para captcha CNPJ no script Gercaptcha.php
Os endereços das consultas são respectivamente:
https://servicos.receita.fazenda.gov.br/Servicos/CPF/ConsultaSituacao/ConsultaPublicaSonoro.asp
http://servicos.receita.fazenda.gov.br/Servicos/cnpjreva/captcha/gerarCaptcha.asp

Para obter o Captcha de CNPJ, é necessário fazer a segunda consulta passando os dados da sessão gravados em cookie.

Como as imagens de captcha também são entregues de maneira diferente nas consultas, é necessário trarar as respostas de maneira diferente conforme as consultas.
Na consulta de CNPJ, é só encodar base 64 a respota da consulta, já na de CPF, tem que extrair da HTML de resposta

Importante lembrar que para a consulta de fato realizada depois para CNPJ (funções.php), deve-se incluir o atributo Flag = 1 no cookie

**Comment by tasca** [comment]
Bom dia Marcos,

Meu caro, não tenho conhecimento em php por isso é dificil pra mim, vc pode
me fazer disso uma API?
ai coloco num servidor pequeno só pro meu uso.
Assim não tenho que reinventar a roda.

Funcionaria assim:

Uma requisiçao GET a API, com parametro CPF, retorna a imagem do captcha,
que a API busca na RF.
Depois envio uma requisição POST com body( CPF, Data nascimento, letras do
captcha), a API busca o nome na RF e devolve esse nome.
O mesmo pra CNPJ.

Veja quanto vai me custar?
Meu whatsapp: 47 99668-5250

Fico no aguardo.

Forte abraço.








Em seg., 3 de mai. de 2021 às 09:36, Marcos Peli ***@***.***>
escreveu:

**Comment by Massa191** [comment]
Olá Ademir Tasca

Conforme conversamos por whats, API pronta aguardando aprovação

Abraço
Marcos Peli

**Comment by tasca** [comment]
Bom dia Peli,

Não acessa devido ao cors, mas pelo index funciona como havia pedido a
vc, então pra mim tá ok.
Veja qual melhor valor que vc pode fazer e fechamos.

tasca

Em qui., 6 de mai. de 2021 às 08:44, Marcos Peli ***@***.***>
escreveu:

**Comment by Massa191** [comment]
API Enviada por email

Abraço
