### ISSUE TITLE
Receita não responde

### ISSUE THREAD

**Issue by lucasborgesbr** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#35]
Boa tarde Marcos,

sabe dizer se houve alguma outra alteração no site da Receita que tenha inviabilizado o uso do seu código?
Simulei ele aqui, e recebo apenas o status de que a receita não responde, (retorno false no curl).

Vi que chegou a criar uma API para um colega também. 

Poderia me auxiliar?

Abraço!

**Comment by Massa191** [comment]
Olá Lucas, boa noite
Desculpe pela demora na resposta

O Projeto continua funcionando normalmente tantonpara consultas CPF quanto para CNPJ

**Comment by lucasborgesbr** [comment]
Oi Marcos, aparentemente era alguma indisponibilidade na receita ou cache aqui também. Tudo funcionando beleza! Obrigado
