### ISSUE TITLE
Consulta por CPF parou de funcionar

### ISSUE THREAD

**Issue by marcotropeco** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#4]
Boa noite Massa,

Você notou que a consulta por CPF parou de funcionar?,

Sempre que consulto aparece o status = "Receita não responde",

Sabe o motivo?, 

Tentei achar algo relacionado a este problema e nada,

Obrigado.

**Comment by marcotropeco** [comment]
Encontrei o problema

Acabei de subir,

Obrigado,

Att

**Comment by Bavaresco** [comment]
Para mim ainda continua mostrando o erro:

`Array ( [0] => [1] => [2] => [3] => [4] => [status] => Receita não responde )`

**Comment by marcotropeco** [comment]
Olá bavaresco o erro persiste porque o massa ainda não aceitou minha alteração,
Mas vou te passar :  https://gist.github.com/marcotropeco/86e12e28924e648b95db6e020da435a9

E só alterar essa função do arquivo funções

**Comment by Massa191** [comment]
Olá Pessoal
Desculpem a demora, não tenho entrado muito por aqui e as notificações foram parar no spam .
Amanhã verifico a alteração de @marcotropeco  
Obrigado pela contribuição

**Comment by marcotropeco** [comment]
Obrigado você que implementou o recurso, Vlw
Att,

**Comment by Massa191** [comment]
Scripts Atualizados
CPF voltou a funcionar
Alteradas URLs em getcaptcha.php e funções.php  para geração de captcha e consulta
Adicionado SSL verif em funções.php  para consulta CPF por @marcotropeco 
Abraços

**Comment by Bavaresco** [comment]
Show!
