### ISSUE TITLE
Modificar o resultado da consulta

### ISSUE THREAD

**Issue by Bavaresco** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#5]
Olá, tudo bem?

Estou usando teu script de consulta CPF em um site aqui e é sensacional!

Só tenho uma dúvida, é possível modificar o resultado da consulta? Pois aqui os dados aparecem em um array, no html, e eu queria que aparecessem em parágrafos pra trabalhar CSS neles..?

Envés de mostrar:
`Array ( [0] => 999.999.999-99 [1] => JOAO SANTOS [2] => 99/99/9999 [3] => REGULAR [4] => 99/99/9999</b> [status] => OK )`

Poderia mostrar:

```
<span class="classe">CPF: 999.999.999-99</span>
<span class="classe">Nome: JOAO SANTOS</span>
<span class="classe">Data de Nascimento: 999.999.999-99</span>
<span class="classe">Situação REGULAR</span>
<span class="classe">Data de Inscrição: 999.999.999-99</span>
<span class="classe">Status: OK</span>
```

Valeu cara, muito obrigado!

**Comment by Massa191** [comment]
Claro que sim,  o script foi deixado desta forma justamente para que os utilizadores formatem a saída dos dados  conforme suas necessidades.

No script processa.php , a variável  $campos é um array que contém os dados da consulta
Ao invés de usar o comando print_r do PHP  para exibir o Array sem formatação,  faça da seguinte forma

`<span class="classe">CPF: <?php echo $campos[0]; ?></span>`
`<span class="classe">Nome:<?php echo $campos[1]; ?></span>`

E assim sucessivamente, mostrando cada um dos conteúdos da array $campos que quiser exibir

**Comment by Bavaresco** [comment]
Mestre do céu, muito obrigado!

Funcionando certinho :D

**Comment by Bavaresco** [comment]
Opa, estou reabrindo para tirar uma última dúvida.

Quando eu removo o array ele para de me mostrar o status da consulta, então se eu insiro dados incorretos ele não mostra nada e também não mostra o status...como faço para também mostrar o status "echoando"?

Ignore, já encontrei..dando uma olhada no código e coloquei `echo $campos['status'];` tudo funcionando 👍
