### ISSUE TITLE
Erro E_WARNING: imagejpeg() expects parameter 1 to be resource, boolean given

### ISSUE THREAD

**Issue by Bavaresco** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#6]
Olá Massa191, tudo bem?

Hoje começou a mostrar no meu painel do newrelic o seguinte erro: http://prntscr.com/es1grk

A mensagem de erro é a seguinte:
`E_WARNING: imagejpeg() expects parameter 1 to be resource, boolean given`

O erro está presente no arquivo `getcaptcha.php` na linha `59`. O carregamento da pagina de consulta, quando solicitado, fica bem lento mas carrega.

Saberia me dizer se isto é um problema do meu site, do código ou da própria receita federal?

**Comment by Massa191** [comment]
O site da receita eventualmente passa por instabilidade. 
Eventualmente os problemas são de rotas nas 
Se vc não fez nenhuma alteração nos scripts é prudente aguardar por normalização
Testei a alguns instantes , e está tudo ok

**Comment by Bavaresco** [comment]
Massa191, muito obrigado pela resposta. É realmente era lentidão da receita federal...tudo normal aqui também desde ontem a tarde.

Obrigado!
