### ISSUE TITLE
Erro "imagem digitada incorretamente" em consulta CNPJ

### ISSUE THREAD

**Issue by Bavaresco** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#7]
Olá, boa tarde!

Qualquer consulta CNPJ que é feita o sistema da o erro:
`Array ( [0] => [1] => [2] => [3] => [4] => [5] => [6] => [7] => [8] => [9] => [10] => [11] => [12] => [13] => [14] => [15] => [16] => [17] => [18] => [19] => [20] => [21] => [status] => Imagem digitada incorretamente )`

Mesmo digitando a imagem corretamente e o CNPJ correto, sempre da este erro.

**Já na consulta de CPF está tudo ok.**

**Comment by douglasresendemaciel** [comment]
Eu fiz alguns testes e parece que houve uma mudança no sistema da receita e agora vc precisa passar o CNPJ sem máscara, ou seja, apenas os números para poder funcionar

**Comment by Bavaresco** [comment]
Realmente, sem a máscara funciona normal!!

**Comment by Bavaresco** [comment]
@douglasresendemaciel tu sabe se existe alguma máscara que bloqueie o uso de "/" e "-"?

**Comment by douglasresendemaciel** [comment]
Não entendi, como assim "bloqueie" o uso de / ou -?

**Comment by Bavaresco** [comment]
@douglasresendemaciel para que o cara não insira caracteres especiais em um input, no caso do CNPJ pontos e hífens.

Já resolvi de outra forma esta questão 👍

**Comment by Massa191** [comment]
Olá pessoal
A Consulta de CNPJ sempre foi apenas com os números, ... sem mascaras, 14 dígitos aceitos no input
Abraços
