### ISSUE TITLE
Caracteres com problema na chamada dos dados do CNPJ

### ISSUE THREAD

**Issue by Bavaresco** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#8]
Olá, heheh, mais um issue meu aqui.

O resultado da consulta de CNPJ está vindo com caracteres "bugados" onde tem acentuação, ex:

> Empres�rio (Individual)
> Prepara��o de documentos e servi�os especializados de apoio administrativo

O site já traz no header o meta UTF8 e aparentemente no arquivo `funcoes.php` também está preparado pra isso, mas mesmo assim ele traz estes caracteres quebrados. Seria problema do script ou da receita?

**Comment by Bavaresco** [comment]
**RESOLVIDO:** Adicionei o seguinte _header_ abaixo do `<?php` no arquivo `processa.php`:
`header('Content-Type: text/html; charset=iso-8859-1');`

Caso precise, seria interessante anexar isto ao código principal aqui no git...

**Comment by Massa191** [comment]
No Array de retorno dos dados de CNPJ está tudo ok
o script não retorna dados do tipo informado 

> Empres�rio (Individual)

> Empres�rio (Individual)
Prepara��o de documentos e servi�os especializados de apoio administrativo
