### ISSUE TITLE
Página com HTTPS não chama imagem do capcha

### ISSUE THREAD

**Issue by Bavaresco** [Massa191/Consultas_CNPJ_CPF_Receita_Federal#9]
Olá, boa noite.

Recentemente ativei SSL em um site e a consulta parou de funcionar. Ele carrega os inputs mas não carrega a imagem do captcha...sabe me dizer o pq isto acontece? Já coloquei os códigos de debug no index.php e no getcapcha.php mas não mostra nenhum erro..

![err](https://cloud.githubusercontent.com/assets/13625422/25074958/04bf6f46-22df-11e7-84e4-33146c32caa2.png)

**Comment by Bavaresco** [comment]
**Atualizando o issue** - O problema não é com SSL, em um site sem SSL o problema persiste. Ele demora para aparecera consulta, quando vc insere os dados de CNPJ não retorna nada. E depois não acessa mais o script, o mesmo fica apenas consumindo muita memória do servidor. Em um site aqui o script da consulta de CNPJ apenas está consumindo mais de 2GB de RAM em tempo real. No caso da consulta de CPF está ok.

**Comment by Bavaresco** [comment]
**Atualizando novamente** - A página da consulta em meu site tinha mais ou menos 8 a 9 pessoas consultando em tempo real, então parece-me que o script parava de funcionar...agora eu acessando sozinho, sem mais pessoas ele funciona normal.

**Comment by Massa191** [comment]
o Site da receita eventualmente passa por instabilidades, e quando isso acontece, realmente ocorrem problemas como o relatado.

Para evitar problemas como o relatado, vc. pode tentar usar os parâmetros CURLOPT_LOW_SPEED_LIMIT ,ou  CURLOPT_TIMEOUT , estabelecendo velocidade mínima de transferência ou o tempo limite para espera por dados, respectivamente  , mas com sua utilização, a chance de abortar a consulta quando a receita apresentar lentidão aumenta.
Infelizmente não temos como evitar problemas técnicos de terceiros, principalmente quando este terceiro não presta um serviço decente.

Abraço

**Comment by Massa191** [comment]
Quanto ao SSL de seu site,  não deveria interferir em nada a consulta do CURL

**Comment by Bavaresco** [comment]
Feito.

Defini um `curl_setopt($ch, CURLOPT_TIMEOUT, 30);` para o CNPJ e para CPF.

Neste momento tenho mais ou menos 70 pessoas consultando no script de consulta, atualmente em uso cerca de 2.3GB de RAM em 40 processos no servidor. O que vc sugere além de diminuir o tempo, para que cada consulta use "menos" do servidor? Ou é normal estes dados? 

No caso do `CURLOPT_LOW_SPEED_LIMIT` que valor vc recomendaria?

**Comment by Bavaresco** [comment]
Ou melhor...eu posso definir para que o CURL use apenas uma quantia certa de RAM? Pois pelo que estou acompanhando ele está usando até que tem, chegou a usar 6GB de RAM na consulta de CPF.

Algo como `CURLOPT_MAX_RECV_SPEED_LARGE, 1024` funciona?

**Comment by Massa191** [comment]
Nunca usei este parâmetro , mas ele iria provocar um efeito contrário ao que vc deseja, uma vez que limitaria a velocidade máxima dos dados recebidos.
Outro detalhe é que a transferência dos dados da receita por curl é muito pequena, e portanto não faria sentido limitar velocidade de transferência de dados. Se falássemos em grandes arquivos enviados ou recebidos, e quiséssemos preservar a banda , tudo bem, mas no caso da receita não se aplicaria este tipo de parâmetro.
Eu indicaria a Vc a utilização de CURLOPT_TIMEOUT , em torno de 5 a 10 segundos para a resposta, que é o que um internauta está disposto a esperar por uma consulta deste tipo

**Comment by Massa191** [comment]
Com relação ao consumo da RAM elevado , possivelmente ocorre pela falta da resposta da receita.
Nem imagino como a biblioteca curl processa os protocolos de requisições e respostas , mas a falta de resposta é com ctz a causa.
O pq. Da falta de resposta podem ser diversos motivos, desde instabilidade ou sobrecarga do serviço da receita , ou mesmo de sua hospedagem , passando pela  rota  do tráfego dos dados , ou ainda finalizando por algum mecanismo da própria receita para evitar o uso "indevido" da consulta.
Destas possibilidades, fico com a instabilidade ou sobrecarga do serviço da receita.

**Comment by Bavaresco** [comment]
Certo, deu uma boa esclarecida.. Também acredito que haja algum controle da receita. Pois a consulta de CNPJ não funciona em meu site se tiver mais que 5 pessoas consultando ao mesmo tempo ela para de funcionar e começa a sobrecarregar o server, já a consulta de CPF funciona normal só que vai gradativamente usando mais RAM.

**Comment by Bavaresco** [comment]
Uma ultima dúvida, eu configurei corretamente conforme a print em anexo?
![curl](https://cloud.githubusercontent.com/assets/13625422/25193027/ec3c1454-250b-11e7-8b72-b10ddb28c5cb.png)

**Comment by Massa191** [comment]
Sim
